name: 'deploy'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          # https://github.com/actions/runner/issues/2033
          # https://exerror.com/fatal-detected-dubious-ownership-in-repository/
          git config --global --add safe.directory '*'

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: 'develop'
          git_remote_url: 'ssh://dokku@${{secrets.HOST}}:22/backend'
          ssh_private_key: ${{secrets.SSH_PRIVATE_KEY}}
